### ISSUE TITLE
empty value prevention patch

### ISSUE THREAD

**Issue by bitpusher-real** [mhwest13/Memcached-Munin-Plugin#2]
I was getting errors about empty values for reclaimed. 

Use of uninitialized value $output in concatenation (.) or string at /etc/munin/plugins/memcached_multi_evictions line 547.
reclaimed.value 

Use of uninitialized value $output in concatenation (.) or string at /etc/munin/plugins/memcached_multi_evictions line 597.
reclaimed.value 

Adding $output ||= 0; 
above lines 547 and 597 "fixes" the problem.

**Comment by mhwest13** [comment]
What version of memcached are you using? Could you post a stats dump from one of the nodes you are monitoring with this script.

Thanks.

**Comment by bitpusher-real** [comment]
1.4.2-1ubuntu3

STAT pid 734
STAT uptime 4170450
STAT time 1298423652
STAT version 1.4.2
STAT pointer_size 64
STAT rusage_user 16926.710000
STAT rusage_system 53651.500000
STAT curr_connections 216
STAT total_connections 233738
STAT connection_structures 239
STAT cmd_get 129047933
STAT cmd_set 322763146
STAT cmd_flush 0
STAT get_hits 129047933
STAT get_misses 205370110
STAT delete_misses 27469495
STAT delete_hits 46032144
STAT incr_misses 0
STAT incr_hits 0
STAT decr_misses 0
STAT decr_hits 0
STAT cas_misses 0
STAT cas_hits 0
STAT cas_badval 0
STAT bytes_read 70672340090
STAT bytes_written 27048690840
STAT limit_maxbytes 3864002560
STAT accepting_conns 1
STAT listen_disabled_num 0
STAT threads 4
STAT conn_yields 0
STAT bytes 3313566021
STAT curr_items 19516207
STAT total_items 322763146
STAT evictions 183696984
END

**Comment by mhwest13** [comment]
Ahh, ok so 1.4.2 doesn't have reclaimed items, I guess I was mis-informed. I'll get something put together that will actually disable that from showing up in the graphs entirely if v1.4.2 is detected. Thanks.

**Comment by mhwest13** [comment]
So I've gone ahead and pushed a fix for you're problem which handles the problem in a more appropriate method, or at least that is my perception ;). While yours works, it also means you have to maintain another rrd file for no reason, except to hold 0.

If you use the commit I've pushed it will actually stop you from using that rrd file to draw the graph. This may not seem like much, but on a over loaded munin master, all the unnecessary rrd files you have don't have to open, the better.

Ciao,

https://github.com/mhwest13/Memcached-Munin-Plugin/commit/92b29e066f04bda027742af0cf069dd2ce92f932
