### ISSUE TITLE
"Can't locate Munin/Plugin.pm in @INC"

### ISSUE THREAD

**Issue by benbuckman** [mhwest13/Memcached-Munin-Plugin#3]
Installed the plugin according to the documentation (on ubuntu 9), trying to get it working.

munin-node-configure returns `memcached_multi_  | yes  | no -bytes -commands -conns -evictions -items -memory`

Running /etc/munin/plugins/memcached_multi_bytes directly returns this error:

Can't locate Munin/Plugin.pm in @INC (@INC contains: /etc/perl /usr/local/lib/perl/5.8.8 /usr/local/share/perl/5.8.8 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.8 /usr/share/perl/5.8 /usr/local/lib/site_perl .) at ./memcached_multi_bytes line 76.

I can't find Plugin.pm anywhere in the system, or "Munin::Plugin" (as specified on line 76) in apt-cache, or google. Any suggestions? Thank you!

**Comment by mhwest13** [comment]
This is definitely an interesting one...

  Curious, what version of munin are you using?

**Comment by benbuckman** [comment]
Aha, you hit the nail. I'm running 1.2.5. It's Ubuntu 8 and that's the latest version in the apt-get packages. Even Ubuntu 9 seems to have an old version. Do you think it's wise to manually upgrade?

**Comment by mhwest13** [comment]
Honestly, I don't know how trivial it will be to upgrade from munin 1.2.5 to 1.4.5, I've done this before on CentOS machines, but not on an Ubuntu machine.

If you can, perhaps stand up a temporary machine with the same install and try it before you do it on your main node. This way you can possibly find any gotchas hiding in the winds.

Beyond that, all I can really do is wish you best of luck...
