### ISSUE TITLE
Multi-graph problems

### ISSUE THREAD

**Issue by locojohn** [mhwest13/Memcached-Munin-Plugin#5]
Hello,

Just wanted to make a small note on the issue I am having with the two multi-graphs: memcached_multi_evictions and memcached_multi_items.  The rest are working fine.  The data is generated successfully and I am able to check it using the munin-run, but something goes wrong when creating the graphs.  

Here's the /var/log/munin/munin-graph.log excerpt:

[...]
2011/06/28 19:20:27 Graphed service : ld_tmp (0.22 sec \* 4)
2011/06/28 19:20:28 Graphed service : ld_portage (0.29 sec \* 4)
2011/06/28 19:20:28 Graphed service : slabitemtime_28 (0.25 sec \* 4)
2011/06/28 19:20:28 [PERL WARNING] Use of uninitialized value in concatenation (.) or string at /usr/lib64/perl5/vendor_perl/5.12.4/Munin/Master/GraphOld.pm line 720.
2011/06/28 19:20:28 [PERL WARNING] Use of uninitialized value in subroutine entry at /usr/lib64/perl5/vendor_perl/5.12.4/Munin/Master/GraphOld.pm line 757.
2011/06/28 19:20:28 [PERL WARNING] Use of uninitialized value $filename in concatenation (.) or string at /usr/lib64/perl5/vendor_perl/5.12.4/Munin/Master/GraphOld.pm line 774.
2011/06/28 19:20:28 [PERL WARNING] Use of uninitialized value $filename in concatenation (.) or string at /usr/lib64/perl5/vendor_perl/5.12.4/Munin/Master/GraphOld.pm line 783.
2011/06/28 19:20:28 [PERL WARNING] Use of uninitialized value $filename in concatenation (.) or string at /usr/lib64/perl5/vendor_perl/5.12.4/Munin/Master/GraphOld.pm line 785.
2011/06/28 19:20:28 [PERL WARNING] Use of uninitialized value $filename in concatenation (.) or string at /usr/lib64/perl5/vendor_perl/5.12.4/Munin/Master/GraphOld.pm line 786.
2011/06/28 19:20:28 [PERL WARNING] Use of uninitialized value in concatenation (.) or string at /usr/lib64/perl5/vendor_perl/5.12.4/Munin/Master/GraphOld.pm line 720.
2011/06/28 19:20:28 [PERL WARNING] Use of uninitialized value in subroutine entry at /usr/lib64/perl5/vendor_perl/5.12.4/Munin/Master/GraphOld.pm line 757.
2011/06/28 19:20:28 [PERL WARNING] Use of uninitialized value $filename in concatenation (.) or string at /usr/lib64/perl5/vendor_perl/5.12.4/Munin/Master/GraphOld.pm line 774.
2011/06/28 19:20:28 [PERL WARNING] Use of uninitialized value $filename in concatenation (.) or string at /usr/lib64/perl5/vendor_perl/5.12.4/Munin/Master/GraphOld.pm line 783.
2011/06/28 19:20:28 [PERL WARNING] Use of uninitialized value $filename in concatenation (.) or string at /usr/lib64/perl5/vendor_perl/5.12.4/Munin/Master/GraphOld.pm line 785.
2011/06/28 19:20:28 [PERL WARNING] Use of uninitialized value $filename in concatenation (.) or string at /usr/lib64/perl5/vendor_perl/5.12.4/Munin/Master/GraphOld.pm line 786.
2011/06/28 19:20:28 Graphed service : mysql_qcache (0.35 sec \* 4)
2011/06/28 19:20:28 [RRD ERROR] Unable to graph /var/www/localhost/htdocs/munin/ahlers/beanrweb03/memcached_items-month.png : opening '': No such file or directory
2011/06/28 19:20:28 [RRD ERROR] Unable to graph /var/www/localhost/htdocs/munin/ahlers/beanrweb03/memcached_items-week.png : opening '': No such file or directory
2011/06/28 19:20:28 [RRD ERROR] Unable to graph /var/www/localhost/htdocs/munin/ahlers/beanrweb03/memcached_items-day.png : opening '': No such file or directory
2011/06/28 19:20:28 [RRD ERROR] Unable to graph /var/www/localhost/htdocs/munin/ahlers/beanrweb03/memcached_items-year.png : opening '': No such file or directory
2011/06/28 19:20:28 Graphed service : memcached_items (0.27 sec \* 4)
2011/06/28 19:20:28 Graphed service : slabitems_14 (0.16 sec \* 4)
2011/06/28 19:20:28 Graphed service : slabitems_31 (0.36 sec \* 4)
2011/06/28 19:20:28 Graphed service : slabitems_13 (0.28 sec \* 4)
2011/06/28 19:20:28 Graphed service : slabitems_18 (0.30 sec \* 4)
[...]

Any ideas how to solve it please?

Andrew

**Comment by mhwest13** [comment]
You may want to take this to the mailing list for Munin, I've not seen this issue in my version, and this is the first time anyone has reported this problem to me. I'm not quite sure what would be causing this issue.

**Comment by einyx** [comment]
yes, same problem here, try to specify the type of your graph (default is gauge, but this is derive)
but is munin that appear to be broken anyway.

**Comment by mhwest13** [comment]
Can you do me a favor and provide me the results of the following commands:
munin-run memcached_multi_evictions config
munin-run memcached_multi_items config

Also, is this something you are running into with the latest version of the code I've just put up?

**Comment by einyx** [comment]
I'm gonna try in test environment tomorrow (the latest version)
The problem is the type of data, as i understand the bug is in munin and is been fixed in the 2.0 release.

I GUESS that the problem popup when you try the aggregration against graph that generate DERIVE value,
and munin try to generate GAUGE value (doesn't matter if you specify the value anyway :( )

If you fix that you make me a big favour ;)

**Comment by mhwest13** [comment]
I know how I could fix it in the plugin, but to be honest, it would require storing temporal files and moving the derivative functions out of munin and into the plugin itself. Not exactly something I want to be doing...

I'm inclined to suggest that you upgrade your munin version to 2.x and get some of the other wonderful benefits it has, including bugfixes such as this one ;)

**Comment by einyx** [comment]
yes, but then i can't use your plugin (the readme don't mention 2.0 :D)

**Comment by mhwest13** [comment]
No it works just fine with 2.0 it requires 1.4.x+ to be on the master / client to support the multigraph capabilities. Those are in munin moving forward, so its fully 2.0 compliant at this point... I don't run a 1.4.x munin anymore since 2.0.x became stable.
